name: dockerImage 

on: 
  workflow_run:
    workflows: ["Pytest","SecurityScanner"]
    types: 
        - completed

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: user/app:${{ github.sha }}
