name: DevSecOpsTask1

#Trigger workflow on pull requests and push
on:
  pull_request:
  push:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest      
        
    steps:
      
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          #Caching packages dependencies
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - run: echo "Python has been set up."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt && pip install -r requirements-dev.txt
      - run: echo "Dependencies have been installed."

      - name: Run tests with pytest
        #Using all available CPU-cores with -n auto
        #Measure code coverage during the test with --cov
        run: pytest -n auto --cov=note_api tests/ --cov-report=xml
      
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - run: echo "Pytest has been executed. Job status is ${{ job.status }}."

security_scan:
    name: Run Security Scan
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Dieser Schritt checkt den aktuellen Stand des Repositorys aus.

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        # Hier wird Python in der Version 3.x eingerichtet, um sicherzustellen, dass die Sicherheitsanalyse durchgeführt werden kann.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Installiert alle Abhängigkeiten aus der requirements.txt, um sicherzustellen, dass der Sicherheits-Scan alle Bibliotheken analysieren kann.

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        with:
          command: test --sarif-file-output=results.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # Führt einen Sicherheits-Scan mit Snyk durch und speichert die Ergebnisse in einer SARIF-Datei namens results.sarif.
        # Ein Snyk API-Token ist erforderlich und muss als Geheimnis hinterlegt sein.

      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
        # Lädt die SARIF-Datei zu GitHub hoch, damit die Ergebnisse der Sicherheitsanalyse direkt im Pull Request angezeigt werden können.

