name: SecurityScanner
on: 
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4  



      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7.4'
          #Caching packages dependencies
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - run: echo "Python has been set up."





      - name: Run Snyk test for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      - name: Run Snyk to monitor project
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor



          